config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :roles
  resources :users, except: [:new]
  get 'posts_imports/new'
  get 'posts_imports/create'
  get 'comments/create'
  get 'comments/destroy'
  root to: 'posts#index'

  # register
  get '/register', to: 'auth#form_register', as: 'form_register'
  post '/register', to: 'auth#register', as: 'register_post'

  # login
  get '/login', to: 'auth#form_login', as: 'form_login'
  post '/login', to: 'auth#login', as: 'login_post'

  # logout
  delete '/logout/:id', to: 'auth#logout', as: 'user_logout'

  resources :posts do
    resources :comments
  end

  resources :searches
  resources :posts_imports, only: %i[new create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/component/_nav.html.erb
<% if session[:userdata] %>
  <header class="py-3 mb-3 border-bottom navbar-light bg-light">
    <div class="container-fluid d-grid gap-3 align-items-center" style="grid-template-columns: 1fr 2fr;">
      <a class="navbar-brand" href="/">Exceltask</a>

      <div class="d-flex align-items-center">
        <%= form_with(url: '/posts', method: 'get', local: true, class: 'w-100 me-3') do %>
          <%= text_field_tag(:search, "", class: "form-control", placeholder: "Search") %>
        <% end %>

        <div class="flex-shrink-0 dropdown">
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
            <!-- <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle"> -->
            <img src="/user.png" width="32" height="32">
          </a>
          <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
            <li><a href="/users/<%= session[:userdata]['id']%>" class='dropdown-item'>Profile (<%= session[:userdata]['username'] %>)</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Logout", user_logout_path(session[:userdata]["id"]), method: :delete, class: 'dropdown-item' %></li>
          </ul>
        </div>
      </div>
    </div>
  </header>
<% end %>

app/views/component/_posts_toolbar.html.erb
<nav class="sticky-top navbar-white bg-white border-bottom">
  <ul class="nav justify-content-between">
    <% if session[:userdata]['role_id'] == 1 %>
      <li class="nav-item">
        <a href="<%= new_posts_import_path %>" class="nav-link">&uarr; XLSX</a>
      </li>
    <% end %>
    <li class="nav-item">
      <a href="<%= posts_path(format: :xlsx, currpage: params[:page], type: "all") %>" class="nav-link">&darr; All</a>
    </li>
    <li class="nav-item">
      <a href="<%= posts_path(format: :xlsx, currpage: params[:page], type: "pageonly") %>" class="nav-link">&darr; Page</a>
    </li>
  </ul>
</nav>