config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :roles
  resources :users, except: [:new]
  get 'posts_imports/new'
  get 'posts_imports/create'
  get 'comments/create'
  get 'comments/destroy'
  root to: 'posts#index'

  # register
  get '/register', to: 'auth#form_register', as: 'form_register'
  post '/register', to: 'auth#register', as: 'register_post'

  # login
  get '/login', to: 'auth#form_login', as: 'form_login'
  post '/login', to: 'auth#login', as: 'login_post'

  # logout
  delete '/logout/:id', to: 'auth#logout', as: 'user_logout'

  resources :posts do
    resources :comments
  end

  resources :searches
  resources :posts_imports, only: %i[new create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/search.rb
# frozen_string_literal: true

# advanced search models
class Search < ApplicationRecord
  paginates_per 10
  self.inheritance_column = 'not_sti'

  def search_post
    post = Post.all

    post = post.where(['title ILIKE ?', "%#{title}%"]) if title.present?
    post = post.order("created_at #{body}") if body.present?

    post
  end
end

app/controllers/searches_controller.rb
# frozen_string_literal: true

# create an advanced search and save to db
class SearchesController < ApplicationController
  before_action :user_signed_in?
  def show
    @search = Search.find(params[:id])
    @posts = @search.search_post.page(params[:page]).per(10)
    @posts = @posts.where(['user_id = ?', session[:userdata]['id'].to_s]) if session[:userdata]['role_id'] != 1
  end

  def new
    @search = Search.new
  end

  def create
    Search.delete_all
    @search = Search.create(search_params)
    redirect_to @search
  end

  private

  def search_params
    params.require(:search).permit(:title, :body)
  end
end

app/helpers/searches_helper.rb
# frozen_string_literal: true

module SearchesHelper
end

app/views/searches/new.html.erb
<h1>Advanced Search</h1>

<div class="my-3">
    <%= form_with model: @search do |f| %>
        <div class="mb-3">
            <%= f.label :title, class: 'form-label' %>
            <%= f.text_field :title, class: "form-control" %>
        </div>

        <div class="mb-3">
            <%= f.label 'Sort', class: 'form-label' %>
            <!-- %= f.select :body, [ 'ASC', 'DESC' ], prompt: 'Select One', :class => 'form-control' % -->

            <select class="form-select form-select-sm mb-2" aria-label=".form-select-sm example" name="search[body]" id="search_body">
                <option value="ASC">Ascending</option>
                <option value="DESC">Descending</option>
            </select>
        </div>

        <%= f.submit "Search", class: 'btn btn-primary', data: { disable_with: "Please Wait..." } %>
        <%= link_to 'Back', posts_path, class: "btn btn-secondary" %>
    <% end %>
</div>

app/views/searches/show.html.erb
<div class="row">
  <div>
    <a href="<%= new_search_path %>">&larr; Back</a>
    <h6>Search Results</h6>
    <% if @posts.empty? %>
      <p>No Post were found.</p>
    <% else %>
      <%= render 'component/posts_toolbar' %>
      <div class="row">
        <% @posts.each do |post| %>
          <div class="col-sm-6">
            <div class="card my-2">
              <div class="card-body">
                <h4><%= link_to(post.title, post_path(post)) %></h4>
                <p><%= truncate(post.body, length: 200) %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <hr />
          
      <%= paginate @posts, window: 4 %>
      <%= page_entries_info @posts %>
    <% end %>
  </div>
</div>