config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :roles
  resources :users, except: [:new]
  get 'posts_imports/new'
  get 'posts_imports/create'
  get 'comments/create'
  get 'comments/destroy'
  root to: 'posts#index'

  # register
  get '/register', to: 'auth#form_register', as: 'form_register'
  post '/register', to: 'auth#register', as: 'register_post'

  # login
  get '/login', to: 'auth#form_login', as: 'form_login'
  post '/login', to: 'auth#login', as: 'login_post'

  # logout
  delete '/logout/:id', to: 'auth#logout', as: 'user_logout'

  resources :posts do
    resources :comments
  end

  resources :searches
  resources :posts_imports, only: %i[new create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# frozen_string_literal: true

# post models posted by registered user only
class Post < ApplicationRecord
  paginates_per 10
  has_many :comments, dependent: :destroy # kalau post di delete, comment juga di delete
  validates :title, presence: true
  validates :body, presence: true
  belongs_to :user

  self.inheritance_column = 'not_sti'

  def self.search(search)
    if search
      where(['title ILIKE ?', "%#{search}%"])
    else
      all
    end
  end

  # belum beres, besok bikin tambah create post + image di upload excel
  # validates :imageurl, presence: true
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# posts controller only can accessed if user has logged in
class PostsController < ApplicationController
  before_action :user_signed_in?

  def index
    find_post
    export_excel(params[:currpage].to_i)
    respond_to do |format|
      format.xlsx do
        response.headers['Content-Disposition'] = "attachment; filename=#{DateTime.now}-posts.xlsx"
      end
      format.html { render :index }
      format.json { render json: @posts }
    end
  end

  def find_post
    session[:userdata]['role_id'] == 1 ? find_post_admin : find_post_writer
  end

  def find_post_admin
    @posts = Post.joins(:user).search(params[:search])
                 .select('posts.*, users.id as user_id, users.username, users.role_id')
                 .order('posts.created_at DESC').page(params[:page]).per(10)
  end

  def find_post_writer
    @posts = Post.joins(:user).search(params[:search])
                 .select('posts.*, users.id as user_id, users.username, users.role_id')
                 .order('posts.created_at DESC').page(params[:page]).per(10)
                 .where('user_id = ?', session[:userdata]['id'])
  end

  def export_excel(page)
    thispage = page > 1 ? page - 1 : page
    @pageposts = ExportExcel.new(
      page: thispage,
      role: session[:userdata]['role_id'],
      type: params[:type],
      id: session[:userdata]['id']
    ).export
  end

  def show
    @post = Post.joins(:user).select('posts.*, users.id as user_id, users.username, users.role_id').find(params[:id])
    if @post.user_id == session[:userdata]['id'] || session[:userdata]['role_id'] == 1
      show_response
    else
      redirect_to(posts_path)
    end
  end

  def show_response
    respond_to do |format|
      format.html
	  format.json { render json: @post }
      format.pdf do
        export_pdf
      end
    end
  end

  def export_pdf
    process = ExportPdf.new(post: @post).export
    send_file process, disposition: :inline
    DeletePdfJob.set(wait: 1.minutes).perform_later(@post.id)
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    # @post = Post.find(params[:id])
    if Post.where('id = ?', params[:id]).update(post_params)
      redirect_to post_path(params[:id])
    else
      render :edit
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = session[:userdata]['id']
    redirect_to @post if @post.save
    respond_to do |format|
      format.js
    end
  end

  def respond_create
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image_url)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: @post, local: false, remote: true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", required: true %>
  </div><br>
 
  <div class="form-group">
    <%= f.label 'Content' %>
    <%= f.text_area :body, class: "form-control", required: true %>
  </div><br>

  <div class="form-group">
    <%= f.label 'Image URL' %>
    <%= f.text_field :image_url, class: "form-control", required: true %>
  </div><br>

  <button class="btn btn-primary" type="submit" data-disable-with="Saving...">Proceed</button>
  <%= link_to 'Back', posts_path, class: "btn btn-secondary" %>
<% end %>

app/views/posts/create.js.erb
 $.ajax({
	success: () => {
        $('#post_body').val('')
        $('#post_title').val('')

		$('#error_explanation').append(`
            <% if @post.errors.any? %>
                <div id="error_explanation">
                  <ul class="alert alert-danger alert-dismissible" role="alert">
                    <h6>
                      <%= pluralize(@post.errors.count, "error") %> prohibited
                      this post from being saved:
                    </h6>
                    <% @post.errors.full_messages.each do |msg| %>
                      <li class="mx-4"><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>
		`)
	}
})

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="d-flex">
  <% if session[:userdata]['role_id'] == 1 || session[:userdata]['role_id'] == 2 %>
    <div class="p-2">
      <%= link_to 'Add Post', new_post_path, class: "btn btn-primary" %>
    </div>
  <% end %>
  
  <%= link_to 'Advance search', new_search_path, class: 'p-2 ms-auto' %>
</div>

<div class="row">
  <div class="mt-3">
    <%= render 'component/posts_toolbar' %>
    <div class="row">
      <% @posts.each do |post| %>
        <div class="col-sm-6">
          <div class="card my-2">
            <div class="card-body">
              <h4><%= link_to(post.title, post_path(post.id)) %></h4>
              <strong>Writer: <%= post.username %></strong>
              <p><%= truncate(post.body, length: 200) %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<hr>
<%= paginate @posts, window: 4 %>
<%= page_entries_info @posts %>

app/views/posts/new.html.erb
<div class="container">
	<h1>New Post</h1>
	<div id="error_explanation"></div>
	<%= render 'form' %>
</div> 

app/views/posts/show.html.erb
<div class="container">
    <h1><%= @post.title %></h1>

    <div class="card mx-auto">
        <div class="card-body">
			<img src="<%= @post.image_url  %>" class="img-fluid" loading="lazy" />	   
			<p><%= @post.body %></p>
            <%= link_to('Export PDF', post_path(@post, format: :pdf)) %>
            <p class="text-muted">File will be removed after 1 minute.</p>
            <% if @post.user_id == session[:userdata]["id"] %>
                <a href="<%= edit_post_path(@post) %>" data-turbolinks-action="replace" class="btn btn-primary col">Edit</a>
                <%= link_to('Destroy', post_path(@post),method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger col") %>
            <% end -%>
        </div>
    </div>

    <div class="card p-2 mt-3 mb-5">
        <h5>Comments</h5>
        <% cache @post.comments do %>
            <%= render @post.comments, cached: true %>
        <% end %>
        <div id="comment"></div>
    </div>

    <div class="mb-5">
        <strong>Add a comment:</strong>
        <%= render 'comments/form' %>
    </div>
</div>

app/views/posts/show.pdf.erb
Generated on:
<%= Time.zone.now %>

<div class="container">
    <h1><%= @post.title %></h1>
    <p>Post ID: <%= @post.id %></p>

    <div class="card mx-auto">
        <div class="card-body">
            <p><%= @post.body %></p>
        </div>
    </div>
</div>